services:
  pg-docker:
    image: postgres:14-alpine
    container_name: dev-postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_WEB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev-network

  pgadmin-docker:
    image: dpage/pgadmin4
    container_name: dev-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_ENHANCED_PROTECTION: "False"
    ports:
      - ${PGADMIN_WEB_PORT}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - pg-docker
    networks:
      - dev-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  dev-network:
    driver: bridge