spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/dslist
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      hbm2ddl:
        delimiter:
    properties:
      #jakarta:
        #persistence:
          #schema-generation:
            #create-source: metadata
            #scripts:
              #action: create
              #create-target: create.sql
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
